#!/usr/bin/env python3
"""
gen_font.py — Generate a LovyanGFX GFXfont header from DejaVu Sans TTF.

Covers 0x20-0xFF: ASCII + Latin-1 Supplement (ä ö ü Ä Ö Ü ß é à etc.).

Usage:
    python3 gen_font.py

Output: src/DejaVuSans18_Latin.h

Dependencies:
    pip install freetype-py
"""

from pathlib import Path
import freetype

# ─── Configuration ────────────────────────────────────────────────────────────
TTF_FILE  = "../ESP32_S3_WaveShare_OSCAR_WB_MONITOR/lib/lvgl/scripts/built_in_font/DejaVuSans.ttf"
SIZE_PX   = 13       # target cap-height in pixels — 13px matches fonts::DejaVu18 (18pt @ 72dpi)
REF_CHAR  = 'A'      # character used for height calibration
DPI       = 72
FIRST     = 0x20     # space
LAST      = 0xFF     # end of Latin-1 Supplement
FONT_NAME = "DejaVuSans18_Latin"
OUT_FILE  = f"src/{FONT_NAME}.h"
# ─────────────────────────────────────────────────────────────────────────────


def pack_1bpp(ft_bitmap):
    w     = int(ft_bitmap.width)
    h     = int(ft_bitmap.rows)
    pitch = int(ft_bitmap.pitch)
    buf   = ft_bitmap.buffer
    mode  = getattr(ft_bitmap, "pixel_mode", None)
    step  = pitch
    if pitch < 0:
        pitch = -pitch

    def row(y):
        return (h - 1 - y) if step < 0 else y

    if mode == freetype.FT_PIXEL_MODE_MONO:
        def on(x, y):
            return (buf[row(y) * pitch + (x >> 3)] & (0x80 >> (x & 7))) != 0
    else:
        def on(x, y):
            return buf[row(y) * pitch + x] > 0

    out, acc, bits = bytearray(), 0, 0
    for y in range(h):
        for x in range(w):
            acc = (acc << 1) | (1 if on(x, y) else 0)
            bits += 1
            if bits == 8:
                out.append(acc & 0xFF)
                acc = bits = 0
    if bits:
        out.append((acc << (8 - bits)) & 0xFF)
    return bytes(out), w, h


def clamp_u8(v, label, code):
    if v > 255:
        print(f"  warn: U+{code:04X} {label}={v} clamped to 255")
        return 255
    return max(0, int(v))


def clamp_s8(v):
    return max(-128, min(127, int(v)))


def main():
    script_dir = Path(__file__).resolve().parent
    ttf_path   = (script_dir / TTF_FILE).resolve()
    out_path   = script_dir / OUT_FILE

    print(f"[font] TTF  : {ttf_path}")
    print(f"[font] Range: U+{FIRST:04X}–U+{LAST:04X}  ({LAST - FIRST + 1} chars)")

    face = freetype.Face(str(ttf_path))

    # Auto-scale: find point size so REF_CHAR bitmap height == SIZE_PX
    face.set_char_size(SIZE_PX * 64, 0, DPI, DPI)
    face.load_char(REF_CHAR, freetype.FT_LOAD_DEFAULT)
    face.glyph.render(freetype.FT_RENDER_MODE_MONO)
    ref_h   = face.glyph.bitmap.rows
    size_pt = round(SIZE_PX * SIZE_PX / ref_h) if ref_h > 0 else SIZE_PX
    print(f"[font] '{REF_CHAR}' at {SIZE_PX}pt → {ref_h}px; scaled to {size_pt}pt")
    face.set_char_size(size_pt * 64, 0, DPI, DPI)

    y_advance = int(face.size.height) >> 6
    if y_advance <= 0:
        y_advance = (int(face.size.ascender) - int(face.size.descender)) >> 6
    y_advance = min(y_advance, 255)

    bitmap_bytes = bytearray()
    glyphs       = []

    for code in range(FIRST, LAST + 1):
        idx = face.get_char_index(code)
        if idx == 0 and code != FIRST:          # missing glyph → zero-width placeholder
            glyphs.append((len(bitmap_bytes), 0, 0, max(4, size_pt // 4), 0, 0))
            continue

        face.load_char(chr(code), freetype.FT_LOAD_DEFAULT)
        face.glyph.render(freetype.FT_RENDER_MODE_MONO)
        g = face.glyph
        packed, w, h = pack_1bpp(g.bitmap)

        glyphs.append((
            len(bitmap_bytes),
            clamp_u8(w,                    'width',    code),
            clamp_u8(h,                    'height',   code),
            clamp_u8(int(g.advance.x) >> 6,'xAdvance', code),
            clamp_s8(int(g.bitmap_left)),
            clamp_s8(-int(g.bitmap_top)),
        ))
        bitmap_bytes.extend(packed)

    # ── Generate header ───────────────────────────────────────────────────────
    def hex_block(data, cols=12):
        parts = [f"0x{b:02X}" for b in data]
        return ",\n".join("  " + ", ".join(parts[i:i+cols]) for i in range(0, len(parts), cols))

    guard = f"_{FONT_NAME.upper()}_H_"
    out   = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        f"// DejaVu Sans {SIZE_PX}px, U+{FIRST:04X}–U+{LAST:04X} (ASCII + Latin-1, incl. German umlauts)",
        f"// Generated by gen_font.py  —  {size_pt}pt @ {DPI}dpi",
        "",
        "#include <pgmspace.h>",
        "#include <LovyanGFX.hpp>",
        "",
        f"static const uint8_t {FONT_NAME}Bitmaps[] PROGMEM = {{",
        hex_block(bitmap_bytes) + ",",
        "};",
        "",
        f"static const lgfx::GFXglyph {FONT_NAME}Glyphs[] PROGMEM = {{",
    ]

    for i, (bo, w, h, xa, xo, yo) in enumerate(glyphs):
        ch   = FIRST + i
        disp = chr(ch) if 0x20 <= ch < 0x7F else f"U+{ch:02X}"
        out.append(f"  {{ {bo:6}, {w:3}, {h:3}, {xa:3}, {xo:4}, {yo:4} }},  // '{disp}'")

    out += [
        "};",
        "",
        f"static const lgfx::GFXfont {FONT_NAME} PROGMEM = {{",
        f"  (uint8_t       *){FONT_NAME}Bitmaps,",
        f"  (lgfx::GFXglyph*){FONT_NAME}Glyphs,",
        f"  0x{FIRST:04X}, 0x{LAST:04X}, {y_advance}",
        "};",
        "",
        f"#endif // {guard}",
        "",
    ]

    out_path.write_text("\n".join(out), encoding="utf-8")
    print(f"[font] Written: {out_path}  ({out_path.stat().st_size / 1024:.1f} KB)")
    print(f"[font] Use:  tft.setFont(&{FONT_NAME})")


if __name__ == "__main__":
    main()
